### ISSUE TITLE
Implement VESC CAN protocol

### ISSUE THREAD

**Issue by juliaschatz** [GOFIRST-Robotics/NASA-RMC-2020-RT#1]
https://github.com/GOFIRST-Robotics/NASA-RMC-2020-NorthstarRobotics/blob/master/documentation/doc/bldc_vescs.txt

**Comment by juliaschatz** [comment]
https://github.com/vedderb/bldc/blob/master/comm_can.c

**Comment by JWCS** [comment]
It's already implemented in the rovr_control package, unless you deleted the files.

**Comment by JWCS** [comment]
Leave the lower-level to the controller, focus on the higher-level with the computer. The computer sends the idea of what objective it wants to be in, with data (or data bypassed directly to controller), and the controller implements. It's meaningless to work on the low-level controller coms now (until it's working), but it will be more illuminating and project-directing to focus on the higher-level. You can still use the Danfoss controller anyway until it's working, so there's no immediate pressure.

**Comment by juliaschatz** [comment]
All implemented now. Requires testing on STM32.

**Comment by juliaschatz** [comment]
Implemented and tested.
