### ISSUE TITLE
Fix position PID control

### ISSUE THREAD

**Issue by juliaschatz** [GOFIRST-Robotics/NASA-RMC-2020-RT#10]
The VESC ostensibly has position PID control built in. Unfortunately it looks like this doesn't work unless we have an actual encoder, and not a hall sensor. So we need to either use encoders for all the spaces we need position control for, implement our own controllers, or modify/update our VESC firmware to fix this issue. Personally I'm leaning towards the latter, as I found at least one source that says that this should work.

**Comment by juliaschatz** [comment]
A few things after more research:
a) The position PID on the VESC looks like it's only about a single rotation. This makes it almost useless for us.
b) I found many threads saying that position control doesn't work with halls, and only one that does. Given that my own testing says no, then I'm guessing it doesn't.

So our solution is probably to write our own controllers, since a) makes the VESC position PID useless for us. We just need to crank up the message rate on the controllers we need position control for.

**Comment by JWCS** [comment]
(Meeting recap)
Current or Velocity control on the vesc is the way to go, coupled with an absolute position sensor, such as a limit switch. The vesc is still the immediate PID, with all the safety precautions pre-set in, like ramp rates and limits. The mc is also doing a PID, or just a P, or even just a command, so as long as it doesn't cause a bad problem, it's fine. The mc would do scaling & stuff, beyond PID, if it's doing complex transformations to the data. 
@Hunter Like drivetrain, converting fwd vel & cmd curvature (radius of) to wheel rotations. This would be some sort of custom transformation/curve/distribution, depending on how the robot behaves over sand. 
For current control, for an initial guess/setting, for a fixed "full speed (enough)" setting, the optimal point on torque/current chart would be good.
