### ISSUE TITLE
This shouldn't compile

### ISSUE THREAD

**Issue by JWCS** [GOFIRST-Robotics/NASA-RMC-2020-RT#12]
Have you been compiling before merging PR?
PR #11 should be broken. For the record:
```
void vIndexValue(F32 const * af32_buffer, U8 u8_ind, F32 f32_value){ af32[u8_ind] = f32_value; }
```
Means that the _values of_ af32_buffer, not the buffer itself, are constant, so you can't assign to it. 
This is because the `const` type qualifier being to it's left. An alternative acceptable way to do this is 
`F32 * const cpf32_buffer` which means a constant (read-only) pointer to non-const (writeable) data. 
Another form is `F32 caf32_buffer[const]` which is a constant array (the buffer is read only, can't assign to the buffer variable caf32_buffer) pointing to writeable data. 
Lastly, if you know how big the array should be, exactly, and you can guarentee it at compile time, you can include the size, and the array won't fall in type down to a pointer:
`F32 caf32_buffer[const 4U]` (Const array 4 long (must be true at compile time! (Weakness!))
`F32 caf32_buffer[static const 4U]` (Like above, but implies that there will always be at least 4 elements, so the compiler can optimize (but you have to make sure! On you!)
Lastly, while I mention it, you can write a pointer, which you know can't be null, as 
`F32 pf32[static 1]` instead of `F32 * pf32`
https://stackoverflow.com/questions/3430315/what-is-the-purpose-of-static-keyword-in-array-parameter-of-function-like-char

**Comment by juliaschatz** [comment]
Of course I check that the code compiles before PRing. This isn't my first rodeo. (For the record, it does, and master currently compiles)

Can you please reference a specific line? I can't find where I've made the mistake of assigning to a constant buffer.

**Comment by JWCS** [comment]
It compiles?
[I believe line 20 vesc.c demonstrates what I quoted above](https://github.com/GOFIRST-Robotics/NASA-RMC-2020-RT/blob/57e9a5a9fdb93f0a73ff5edcb211e1261fc109a4/Src/VESC.c#L20)
https://stackoverflow.com/questions/21476869/constant-pointer-vs-pointer-to-constant

**Comment by juliaschatz** [comment]
Neither `vesc_send_message` or `do_send_can_message` modify any elements passed into them. I believe that thus `U8 const* buffer` is the correct way to do this because we want to promise that none of the elements inside the buffer are modified.

**Comment by JWCS** [comment]
Ok, sorry for the misunderstanding. It wasn't clear, to me, from the code that the do_send_can_msg was purely side-effecting, not modifying the vesc. 
This isn't critical, so I'll close the issue (thanks for clarifying). 
A few style things would be to make sure the suffix 'U' is after unsigned integers, such as those constants used to index arrays, and 'F' for F32s, such as line 123. 
If you're not planning on modifying the pointer to a const value, you should also make it const: F32 const *const. 
Lastly, if the vesc being passed in to send the msg is only using it's ID, you should just pass the ID in. 
One could argue, rightly, that passing the whole thing in allows for the function to grow as the functionality grows, but that also points to just writing another function, which, for being smaller, is easier to test. If you find another requirement for more than just the ID, then refactor/grow.
